services:
  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: ntfy
    restart: unless-stopped
    networks:
      - ntfy_network
    command: serve
    environment:
      - TZ=Europe/Moscow
      - NTFY_BASE_URL=https://${DOMAIN}
      - NTFY_BEHIND_PROXY=true
      - NTFY_CACHE_FILE=/var/cache/ntfy/cache.db
      - NTFY_AUTH_FILE=/var/lib/ntfy/user.db
      - NTFY_ATTACHMENT_CACHE_DIR=/var/cache/ntfy/attachments
      - NTFY_AUTH_DEFAULT_ACCESS=deny-all
      - NTFY_AUTH_USERS=nexus:$$2a$$12$$paUdYx29gikrfGpjIT.ZieWWDD6d76eOIQ7wUsCj9rozs2asMPmGK:admin
      - NTFY_ENABLE_LOGIN=true
      - NTFY_REQUIRE_LOGIN=true
    volumes:
      - ntfy-data:/var/lib/ntfy
      - ntfy-cache:/var/cache/ntfy
    ports:
      - "127.0.0.1:3000:80"
  xray-checker:
    image: kutovoys/xray-checker
    container_name: checker
    env_file: .env
    networks:
      - ntfy_network
    environment:
      - SUBSCRIPTION_UPDATE=true
      - SUBSCRIPTION_UPDATE_INTERVAL=300
      - PROXY_CHECK_INTERVAL=450
      - PROXY_CHECK_METHOD=status
      - PROXY_TIMEOUT=30
      - PROXY_IP_CHECK_URL=https://api.ipify.org?format=text
      - PROXY_STATUS_CHECK_URL=http://youtube.com/generate_204
      - PROXY_DOWNLOAD_URL=https://proof.ovh.net/files/1Mb.dat
      - PROXY_DOWNLOAD_TIMEOUT=60
      - PROXY_DOWNLOAD_MIN_SIZE=51200
      - PROXY_RESOLVE_DOMAINS=false
      - SIMULATE_LATENCY=true
      - XRAY_START_PORT=10000
      - XRAY_LOG_LEVEL=none
      - WEB_SHOW_DETAILS=false
      - WEB_PUBLIC=false
      - LOG_LEVEL=info
      - RUN_ONCE=false
    ports:
      - "127.0.0.1:2112:2112"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:2112/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
volumes:
  ntfy-data:
  ntfy-cache:
networks:
  ntfy_network: